layout_spectrum: 0.1630769
typography_spectrum: 0.407384
color:
  saturation: 0.3671758
  lightness: 0.9834188
  brandStrength: 0.1992184
  rhythmicContrast: 0.9023201
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: OurStories
